In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
url='https://join.com/recruitment-hr-blog/best-job-sites-in-spain'

page= requests.get(url)

In [3]:
soup = BeautifulSoup(page.text, 'html')

In [4]:
tags= soup.find_all('h3')
print(tags)

[<h3 class="wp-block-heading">1. Infojobs</h3>, <h3 class="wp-block-heading">2. Tecnoempleo</h3>, <h3 class="wp-block-heading">3. LinkedIn</h3>, <h3 class="wp-block-heading">4. Indeed</h3>, <h3 class="wp-block-heading">5. Infoempleo</h3>, <h3 class="wp-block-heading">6. Monster</h3>, <h3 class="wp-block-heading">7. Rviewer</h3>, <h3 class="wp-block-heading">8. Jobrapido</h3>, <h3 class="wp-block-heading">9. Remotive</h3>, <h3 class="wp-block-heading">10. Relocate.me</h3>, <h3 class="wp-block-heading">11. Experteer</h3>, <h3 class="wp-block-heading">12. FlexJobs</h3>, <h3 class="wp-block-heading">Effect of the market on job sites in Spain</h3>, <h3 class="wp-block-heading">Language and location</h3>, <h3 class="wp-block-heading">Further helpful resources to recruit abroad</h3>]

In [7]:
websites = [tag.text.strip() for tag in tags]
websites

['1. Infojobs',
 '2. Tecnoempleo',
 '3. LinkedIn',
 '4. Indeed',
 '5. Infoempleo',
 '6. Monster',
 '7. Rviewer',
 '8. Jobrapido',
 '9. Remotive',
 '10. Relocate.me',
 '11. Experteer',
 '12. FlexJobs',
 'Effect of the market on job sites in Spain',
 'Language and location',
 'Further helpful resources to recruit abroad']

In [8]:
Top_websites = [site.split('. ',1)[1] for site in websites[0:12]]
Top_websites

['Infojobs',
 'Tecnoempleo',
 'LinkedIn',
 'Indeed',
 'Infoempleo',
 'Monster',
 'Rviewer',
 'Jobrapido',
 'Remotive',
 'Relocate.me',
 'Experteer',
 'FlexJobs']

In [9]:
df = pd.DataFrame(Top_websites , columns=['Top Websites for Remote Jobs in Spain'])
df

   Top Websites for Remote Jobs in Spain
0                               Infojobs
1                            Tecnoempleo
2                               LinkedIn
3                                 Indeed
4                             Infoempleo
5                                Monster
6                                Rviewer
7                              Jobrapido
8                               Remotive
9                            Relocate.me
10                             Experteer
11                              FlexJobs

In [10]:
df.insert(0, 'Rank', range(1, len(df)+1))

In [11]:
df

    Rank Top Websites for Remote Jobs in Spain
0      1                              Infojobs
1      2                           Tecnoempleo
2      3                              LinkedIn
3      4                                Indeed
4      5                            Infoempleo
5      6                               Monster
6      7                               Rviewer
7      8                             Jobrapido
8      9                              Remotive
9     10                           Relocate.me
10    11                             Experteer
11    12                              FlexJobs

In [12]:
df.rename(columns={"Rank": "Website Ranking"}, inplace=True)

In [13]:
df

    Website Ranking Top Websites for Remote Jobs in Spain
0                 1                              Infojobs
1                 2                           Tecnoempleo
2                 3                              LinkedIn
3                 4                                Indeed
4                 5                            Infoempleo
5                 6                               Monster
6                 7                               Rviewer
7                 8                             Jobrapido
8                 9                              Remotive
9                10                           Relocate.me
10               11                             Experteer
11               12                              FlexJobs

In [17]:
df.to_csv(r'C:/Users/HOME/OneDrive/Documents/Projects/Top_Websites.csv', index=False)

In [18]:
output_file= pd.read_csv('C:/Users/HOME/OneDrive/Documents/Projects/Top_Websites.csv')
output_file

    Website Ranking Top Websites for Remote Jobs in Spain
0                 1                              Infojobs
1                 2                           Tecnoempleo
2                 3                              LinkedIn
3                 4                                Indeed
4                 5                            Infoempleo
5                 6                               Monster
6                 7                               Rviewer
7                 8                             Jobrapido
8                 9                              Remotive
9                10                           Relocate.me
10               11                             Experteer
11               12                              FlexJobs